// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjvi263KhEc6pzafOlutXCSk85nW6QrOk',
    appId: '1:450350240893:web:f9c9213f875fd28f42cd14',
    messagingSenderId: '450350240893',
    projectId: 'flash-chat-firebase-sample',
    authDomain: 'flash-chat-firebase-sample.firebaseapp.com',
    storageBucket: 'flash-chat-firebase-sample.appspot.com',
    measurementId: 'G-06SDX7JGZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgwsT5sa10TiPNOTnuTtTX3y5na1xPbpE',
    appId: '1:450350240893:android:3a9a649960b0039242cd14',
    messagingSenderId: '450350240893',
    projectId: 'flash-chat-firebase-sample',
    storageBucket: 'flash-chat-firebase-sample.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfFoc0c19nTuEi4EpoNVANY3KCywo1SC0',
    appId: '1:450350240893:ios:a6433fc60fcf513d42cd14',
    messagingSenderId: '450350240893',
    projectId: 'flash-chat-firebase-sample',
    storageBucket: 'flash-chat-firebase-sample.appspot.com',
    iosClientId: '450350240893-mnvp4sb7kr098ns8nirgn6g9k2vr76sk.apps.googleusercontent.com',
    iosBundleId: 'co.appbrewery.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfFoc0c19nTuEi4EpoNVANY3KCywo1SC0',
    appId: '1:450350240893:ios:a6433fc60fcf513d42cd14',
    messagingSenderId: '450350240893',
    projectId: 'flash-chat-firebase-sample',
    storageBucket: 'flash-chat-firebase-sample.appspot.com',
    iosClientId: '450350240893-mnvp4sb7kr098ns8nirgn6g9k2vr76sk.apps.googleusercontent.com',
    iosBundleId: 'co.appbrewery.flashChat',
  );
}
